lint:
  files_exist: false
    - assets/nf-core-metaval_logo_light.png
    - docs/images/nf-core-metaval_logo_light.png
    - docs/images/nf-core-metaval_logo_dark.png
  files_unchanged: false
    - assets/sendmail_template.txt
    - .github/CONTRIBUTING.md
    - .github/ISSUE_TEMPLATE/bug_report.yml
    - .github/PULL_REQUEST_TEMPLATE.md
    - .github/workflows/linting.yml
    - .github/workflows/branch.yml
    - .github/ISSUE_TEMPLATE/feature_request.yml
    - assets/email_template.html
    - assets/email_template.txt
    - docs/README.md
    - pyproject.toml
repository_type: pipeline
template:
  author: LilyAnderssonLee
  description: Taxprofiler post-processing: verification of predicted species from nf-core/taxprofiler
  name: metaval
  prefix: genomic-medicine-sweden
