lint:
  files_exist: false
    - assets/nf-core-meta-val_logo_light.png
    - docs/images/nf-core-meta-val_logo_light.png
    - docs/images/nf-core-meta-val_logo_dark.png
    - assets/samplesheet.csv
  files_unchanged: false
    - assets/sendmail_template.txt
    - .github/CONTRIBUTING.md
    - .github/ISSUE_TEMPLATE/bug_report.yml
    - .github/PULL_REQUEST_TEMPLATE.md
    - .github/workflows/linting.yml
    - .github/workflows/branch.yml
    - .github/ISSUE_TEMPLATE/feature_request.yml
    - assets/email_template.html
    - assets/email_template.txt
    - docs/README.md
    - viralPathogenList.csv

  multiqc_config:
    - report_comment

  nextflow_config:
    - manifest.name
    - manifest.homePage

repository_type: pipeline
template:
  author: LilyAnderssonLee
  description: nf-core/taxprofiler post processing
  name: metaval
  prefix: genomic-medicine-sweden
nf_core_version: "2.14.1"
