contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #metaval channel"
    url: https://nfcore.slack.com/channels/metaval
    about: Discussion about the genomic-medicine-sweden/meta-val pipeline
